name: Check Code Format by Prettier & Test by Jest

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - 'main'

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run prettier-check
      - run: npm run test
