name: Check Code Format by Prettier & Test by Jest

on:
  push:
    branches:
      - 'main'

jobs:
  install-pack:
    name: Install all package
    runs-on: ubuntu-latest
    steps:
      - name: Cheack
        uses: actions/checkout@v2
      - runs: npm install
      - runs: npm run prettier-check
      - runs: npm run test
